version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translation_service
    ports:
      - '3306:3306'
